#!/usr/bin/env bash

# 1. Create a color palette file
ffmpeg -i balls.mp4 -vf "fps=10,scale=800:-1:flags=lanczos,palettegen" palette.png

# 2. Use the palette to create the GIF
ffmpeg -i balls.mp4 -i palette.png -filter_complex "fps=10,scale=800:-1:flags=lanczos[x];[x][1:v]paletteuse" output.gif
